package Presentacion;

import Negocio.Libro;
import Negocio.Prestamo;
import java.awt.Graphics;
import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class AgregarPrestamo extends javax.swing.JFrame {
    /**
     * Creates new form AgregarLector
     */
    Libro libros = new Libro();
    FondoPanel fondo = new FondoPanel();
    /*
    String autorLibro1Antiguo = "";
    String autorLibro2Antiguo = "";
    String autorLibro3Antiguo = "";
    String autorLibro4Antiguo = "";
    String autorLibro5Antiguo = "";
    String nombreLibro1Antiguo = "";
    String nombreLibro2Antiguo = "";
    String nombreLibro3Antiguo = "";
    String nombreLibro4Antiguo = "";
    String nombreLibro5Antiguo = "";
    */
    public AgregarPrestamo() {
        this.setContentPane(fondo);
        
        initComponents();
        setTitle("Agregar nuevo lector");
        setLocationRelativeTo(null);
        libros.ListadoAutoresLibros(textAutorLibro1);
        libros.ListadoAutoresLibros(textAutorLibro2);
        libros.ListadoAutoresLibros(textAutorLibro3);
        libros.ListadoAutoresLibros(textAutorLibro4);
        libros.ListadoAutoresLibros(textAutorLibro5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesSiNo = new javax.swing.ButtonGroup();
        calendarPanel1 = new com.github.lgooddatepicker.components.CalendarPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textApellido = new javax.swing.JTextField();
        textFechaPrestamo = new javax.swing.JTextField();
        textTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textFechaDevolucion = new javax.swing.JTextField();
        textNombreLibro1 = new javax.swing.JComboBox<>();
        textAutorLibro1 = new javax.swing.JComboBox<>();
        textIdLibro1 = new javax.swing.JTextField();
        textPrecioLibro1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textIdLibro2 = new javax.swing.JTextField();
        textAutorLibro2 = new javax.swing.JComboBox<>();
        textNombreLibro2 = new javax.swing.JComboBox<>();
        textPrecioLibro2 = new javax.swing.JTextField();
        textPrecioLibro3 = new javax.swing.JTextField();
        textIdLibro4 = new javax.swing.JTextField();
        textAutorLibro4 = new javax.swing.JComboBox<>();
        textNombreLibro4 = new javax.swing.JComboBox<>();
        textPrecioLibro4 = new javax.swing.JTextField();
        textNombreLibro3 = new javax.swing.JComboBox<>();
        textAutorLibro3 = new javax.swing.JComboBox<>();
        textIdLibro3 = new javax.swing.JTextField();
        textIdLibro5 = new javax.swing.JTextField();
        textAutorLibro5 = new javax.swing.JComboBox<>();
        textNombreLibro5 = new javax.swing.JComboBox<>();
        textPrecioLibro5 = new javax.swing.JTextField();
        botonEstado = new javax.swing.JRadioButton();
        textIdPrestamo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Nombre");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Apellido");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Fecha prestamo");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        textNombre.setEditable(false);

        textApellido.setEditable(false);

        textFechaPrestamo.setText("dd/mm/aaaa");

        textTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Salir");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Nuevo prestamo");
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("ID Asociado");
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));

        textId.setEditable(false);

        jLabel13.setText("Fecha devolución");
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));

        textFechaDevolucion.setText("dd/mm/aaaa");

        textNombreLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreLibro1ActionPerformed(evt);
            }
        });

        textAutorLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAutorLibro1ActionPerformed(evt);
            }
        });

        textIdLibro1.setEditable(false);

        textPrecioLibro1.setEditable(false);
        textPrecioLibro1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textPrecioLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrecioLibro1ActionPerformed(evt);
            }
        });

        jLabel3.setText("ID");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Autor");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Nombre Libro");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Precio");
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Total");
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));

        textIdLibro2.setEditable(false);

        textAutorLibro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAutorLibro2ActionPerformed(evt);
            }
        });

        textNombreLibro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreLibro2ActionPerformed(evt);
            }
        });

        textPrecioLibro2.setEditable(false);
        textPrecioLibro2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textPrecioLibro3.setEditable(false);
        textPrecioLibro3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textIdLibro4.setEditable(false);

        textAutorLibro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAutorLibro4ActionPerformed(evt);
            }
        });

        textNombreLibro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreLibro4ActionPerformed(evt);
            }
        });

        textPrecioLibro4.setEditable(false);
        textPrecioLibro4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textNombreLibro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreLibro3ActionPerformed(evt);
            }
        });

        textAutorLibro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAutorLibro3ActionPerformed(evt);
            }
        });

        textIdLibro3.setEditable(false);

        textIdLibro5.setEditable(false);

        textAutorLibro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAutorLibro5ActionPerformed(evt);
            }
        });

        textNombreLibro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreLibro5ActionPerformed(evt);
            }
        });

        textPrecioLibro5.setEditable(false);
        textPrecioLibro5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        botonEstado.setText("Estado");
        botonEstado.setEnabled(false);
        botonEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonEstado.setForeground(new java.awt.Color(255, 255, 255));

        textIdPrestamo.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID Prestamo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEstado))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(textIdLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textAutorLibro1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(textIdLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textAutorLibro2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNombreLibro1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textNombreLibro2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textPrecioLibro1)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textPrecioLibro2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textIdLibro5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textAutorLibro5, 0, 202, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textIdLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textIdLibro4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textAutorLibro3, 0, 202, Short.MAX_VALUE)
                                            .addComponent(textAutorLibro4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textNombreLibro4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(textNombreLibro3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textPrecioLibro3)
                                            .addComponent(textPrecioLibro4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(textNombreLibro5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textPrecioLibro5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(578, 578, 578)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(textNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textFechaPrestamo)
                                            .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(71, 71, 71)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textApellido)
                                            .addComponent(textFechaDevolucion)
                                            .addComponent(textIdPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(textFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombreLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAutorLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textIdLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPrecioLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombreLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAutorLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textIdLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPrecioLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNombreLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPrecioLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNombreLibro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPrecioLibro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textAutorLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textIdLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textAutorLibro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textIdLibro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIdLibro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAutorLibro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNombreLibro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPrecioLibro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jToggleButton1)
                    .addComponent(botonEstado))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        //Al oprimir el botón "Salir", nos regresa a la ventana "Prestamos"
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Prestamo nuevo = new Prestamo();
        //nuevo.Conectar();//Eliminar
        int contadorLibros = 0;
        float costoTotal = 0;
        
        if(!textIdLibro1.getText().equals(""))
        {
            contadorLibros++;
            costoTotal += Float.parseFloat(textPrecioLibro1.getText());
            nuevo.setIdLibro1(Integer.parseInt(textIdLibro1.getText()));
        }
        else
        {
            nuevo.setIdLibro1(0);
        }
        if(!textIdLibro2.getText().equals(""))
        {
            contadorLibros++;
            costoTotal += Float.parseFloat(textPrecioLibro2.getText());
            nuevo.setIdLibro2(Integer.parseInt(textIdLibro2.getText()));
        }
        else
        {
            nuevo.setIdLibro2(0);
        }
        if(!textIdLibro3.getText().equals(""))
        {
            contadorLibros++;
            costoTotal += Float.parseFloat(textPrecioLibro3.getText());
            nuevo.setIdLibro3(Integer.parseInt(textIdLibro3.getText()));
        }
        else
        {
            nuevo.setIdLibro3(0);
        }
        if(!textIdLibro4.getText().equals(""))
        {
            contadorLibros++;
            costoTotal += Float.parseFloat(textPrecioLibro4.getText());
            nuevo.setIdLibro4(Integer.parseInt(textIdLibro4.getText()));
        }
        else
        {
            nuevo.setIdLibro4(0);
        }
        if(!textIdLibro5.getText().equals(""))
        {
            contadorLibros++;
            costoTotal += Float.parseFloat(textPrecioLibro5.getText());
            nuevo.setIdLibro5(Integer.parseInt(textIdLibro5.getText()));
        }
        else
        {
            nuevo.setIdLibro5(0);
        }
        
        nuevo.setLectorId(Integer.parseInt(textId.getText()));
        nuevo.setNombreLector(textNombre.getText());
        nuevo.setApellidoLector(textApellido.getText());
        nuevo.setCantidadLibros(contadorLibros);
        nuevo.setCostoTotal(costoTotal);
        DateTimeFormatter JEFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        nuevo.setFechaPrestamo(LocalDate.parse(textFechaPrestamo.getText(), JEFormatter));
        nuevo.setFechaDevolucion(LocalDate.parse(textFechaDevolucion.getText(), JEFormatter));
        nuevo.setEstado(true);
        
        if (botonEstado.isSelected() == false){
            nuevo.Agregar();
        }
        else{
            nuevo.setId(Integer.parseInt(textIdPrestamo.getText()));
            nuevo.Modificar();
        }
        //nuevo.Desconectar();//Eliminar
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void textAutorLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAutorLibro1ActionPerformed
        // TODO add your handling code here:
        //System.out.println("Autor libro 1: " + textAutorLibro1.getSelectedItem());
        autorLibroListado(textAutorLibro1, textNombreLibro1, textIdLibro1, textPrecioLibro1);
        /*
        if(autorLibro1Antiguo.equals(textAutorLibro1.getSelectedItem().toString()))
        {
            System.out.println("Verdadero");
            autorLibroListado(textAutorLibro1, textNombreLibro1, textIdLibro1, textPrecioLibro1);
            autorLibro1Antiguo = textAutorLibro1.getSelectedItem().toString();
            System.out.println(autorLibro1Antiguo);
        }
        else
        {
            System.out.println("Falso");
        }
        */
    }//GEN-LAST:event_textAutorLibro1ActionPerformed

    private void textNombreLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreLibro1ActionPerformed
        // TODO add your handling code here:
        //System.out.println("Nombre libro 1: " + textNombreLibro1.getSelectedItem());
        nombreLibroListado(textNombreLibro1, textAutorLibro1, textIdLibro1, textPrecioLibro1);
        /*
        if(nombreLibro1Antiguo.equals(textNombreLibro1.getSelectedItem().toString()))
        {
            System.out.println("Verdadero");
            nombreLibroListado(textNombreLibro1, textAutorLibro1, textIdLibro1, textPrecioLibro1);
            nombreLibro1Antiguo = textNombreLibro1.getSelectedItem().toString();
            System.out.println(nombreLibro1Antiguo);
        }
        else
        {
            System.out.println("Falso");
        }
        */
    }//GEN-LAST:event_textNombreLibro1ActionPerformed

    private void textAutorLibro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAutorLibro2ActionPerformed
        // TODO add your handling code here:
        //System.out.println("Autor libro 2: " + textAutorLibro2.getSelectedItem());
        autorLibroListado(textAutorLibro2, textNombreLibro2, textIdLibro2, textPrecioLibro2);
    }//GEN-LAST:event_textAutorLibro2ActionPerformed

    private void textNombreLibro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreLibro2ActionPerformed
        // TODO add your handling code here:
        //System.out.println("Nombre libro 2: " + textNombreLibro2.getSelectedItem());
        nombreLibroListado(textNombreLibro2, textAutorLibro2, textIdLibro2, textPrecioLibro2);
    }//GEN-LAST:event_textNombreLibro2ActionPerformed

    private void textAutorLibro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAutorLibro4ActionPerformed
        // TODO add your handling code here:
        //System.out.println("Autor libro 4: " + textAutorLibro4.getSelectedItem());
        autorLibroListado(textAutorLibro4, textNombreLibro4, textIdLibro4, textPrecioLibro4);
    }//GEN-LAST:event_textAutorLibro4ActionPerformed

    private void textNombreLibro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreLibro4ActionPerformed
        // TODO add your handling code here:
        //System.out.println("Nombre libro 4: " + textNombreLibro4.getSelectedItem());
        nombreLibroListado(textNombreLibro4, textAutorLibro4, textIdLibro4, textPrecioLibro4);
    }//GEN-LAST:event_textNombreLibro4ActionPerformed

    private void textNombreLibro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreLibro3ActionPerformed
        // TODO add your handling code here:
        //System.out.println("Nombre libro 3: " + textNombreLibro3.getSelectedItem());
        nombreLibroListado(textNombreLibro3, textAutorLibro3, textIdLibro3, textPrecioLibro3);
    }//GEN-LAST:event_textNombreLibro3ActionPerformed

    private void textAutorLibro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAutorLibro3ActionPerformed
        // TODO add your handling code here:
        //System.out.println("Autor libro 3: " + textAutorLibro3.getSelectedItem());
        autorLibroListado(textAutorLibro3, textNombreLibro3, textIdLibro3, textPrecioLibro3);
    }//GEN-LAST:event_textAutorLibro3ActionPerformed

    private void textAutorLibro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAutorLibro5ActionPerformed
        // TODO add your handling code here:
        //System.out.println("Autor libro 5: " + textAutorLibro5.getSelectedItem());
        autorLibroListado(textAutorLibro5, textNombreLibro5, textIdLibro5, textPrecioLibro5);
    }//GEN-LAST:event_textAutorLibro5ActionPerformed

    private void textNombreLibro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreLibro5ActionPerformed
        // TODO add your handling code here:
        //System.out.println("Nombre libro 5: " + textNombreLibro5.getSelectedItem());
        nombreLibroListado(textNombreLibro5, textAutorLibro5, textIdLibro5, textPrecioLibro5);
    }//GEN-LAST:event_textNombreLibro5ActionPerformed

    private void textPrecioLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrecioLibro1ActionPerformed
        // TODO add your handling code here:
        System.out.println("Cambio el valor");
    }//GEN-LAST:event_textPrecioLibro1ActionPerformed
    
    public void Cargar(int idModificar, String nombreModificar, String apellidoModificar){
        textId.setText(String.valueOf(idModificar));
        textNombre.setText(nombreModificar);
        textApellido.setText(apellidoModificar);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonEstado;
    private javax.swing.ButtonGroup botonesSiNo;
    private com.github.lgooddatepicker.components.CalendarPanel calendarPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField textApellido;
    private javax.swing.JComboBox<String> textAutorLibro1;
    private javax.swing.JComboBox<String> textAutorLibro2;
    private javax.swing.JComboBox<String> textAutorLibro3;
    private javax.swing.JComboBox<String> textAutorLibro4;
    private javax.swing.JComboBox<String> textAutorLibro5;
    private javax.swing.JTextField textFechaDevolucion;
    private javax.swing.JTextField textFechaPrestamo;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textIdLibro1;
    private javax.swing.JTextField textIdLibro2;
    private javax.swing.JTextField textIdLibro3;
    private javax.swing.JTextField textIdLibro4;
    private javax.swing.JTextField textIdLibro5;
    private javax.swing.JTextField textIdPrestamo;
    private javax.swing.JTextField textNombre;
    private javax.swing.JComboBox<String> textNombreLibro1;
    private javax.swing.JComboBox<String> textNombreLibro2;
    private javax.swing.JComboBox<String> textNombreLibro3;
    private javax.swing.JComboBox<String> textNombreLibro4;
    private javax.swing.JComboBox<String> textNombreLibro5;
    private javax.swing.JTextField textPrecioLibro1;
    private javax.swing.JTextField textPrecioLibro2;
    private javax.swing.JTextField textPrecioLibro3;
    private javax.swing.JTextField textPrecioLibro4;
    private javax.swing.JTextField textPrecioLibro5;
    private javax.swing.JTextField textTotal;
    // End of variables declaration//GEN-END:variables

    //Se le coloca una imagen como fondo de pantalla
    class FondoPanel extends JPanel{
        private Image imagen;
        
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/Imagenes/Biblioteca.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    public void Cargar(int idModificar, String nombreModificar, String apellidoModificar, int idPrestamoModificar, String fechaPrestamoModificar, 
                       String fechaDevolucionModificar, String nombreLibro1Modificar, String nombreLibro2Modificar, 
                       String nombreLibro3Modificar, String nombreLibro4Modificar, String nombreLibro5Modificar, String autorLibro1Modificar, 
                       String autorLibro2Modificar, String autorLibro3Modificar, String autorLibro4Modificar, String autorLibro5Modificar, 
                       Boolean estado)
    { 
        textId.setText(String.valueOf(idModificar));
        textNombre.setText(nombreModificar);
        textApellido.setText(apellidoModificar);
        textIdPrestamo.setText(String.valueOf(idPrestamoModificar));
        textAutorLibro1.setSelectedItem(autorLibro1Modificar);
        textNombreLibro1.setSelectedItem(nombreLibro1Modificar);
        textAutorLibro2.setSelectedItem(autorLibro2Modificar);
        textNombreLibro2.setSelectedItem(nombreLibro2Modificar);
        textAutorLibro3.setSelectedItem(autorLibro3Modificar);
        textNombreLibro3.setSelectedItem(nombreLibro3Modificar);
        textAutorLibro4.setSelectedItem(autorLibro4Modificar);
        textNombreLibro4.setSelectedItem(nombreLibro4Modificar);
        textAutorLibro5.setSelectedItem(autorLibro5Modificar);
        textNombreLibro5.setSelectedItem(nombreLibro5Modificar);
        
        //Formato inicial.  
        SimpleDateFormat formato1 = new SimpleDateFormat("yyyy-MM-dd");
        
        try {
            Date d = formato1.parse(fechaPrestamoModificar);
            
            //Aplica formato requerido.
            formato1.applyPattern("dd/MM/yyyy");
            String nuevoFormato = formato1.format(d);
            textFechaPrestamo.setText(nuevoFormato);
        } catch (ParseException ex) {
            Logger.getLogger(AgregarPrestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Formato inicial.  
        SimpleDateFormat formato2 = new SimpleDateFormat("yyyy-MM-dd");
        
        try {
            Date d = formato2.parse(fechaDevolucionModificar);
            
            //Aplica formato requerido.
            formato2.applyPattern("dd/MM/yyyy");
            String nuevoFormato = formato2.format(d);
            textFechaDevolucion.setText(nuevoFormato);
        } catch (ParseException ex) {
            Logger.getLogger(AgregarPrestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /*
        textAutorLibro1.setSelectedItem(autorLibro1Modificar);
        textNombreLibro1.setSelectedItem(nombreLibro1Modificar);
        textAutorLibro2.setSelectedItem(autorLibro2Modificar);
        textNombreLibro2.setSelectedItem(nombreLibro2Modificar);
        textAutorLibro3.setSelectedItem(autorLibro3Modificar);
        textNombreLibro3.setSelectedItem(nombreLibro3Modificar);
        textAutorLibro4.setSelectedItem(autorLibro4Modificar);
        textNombreLibro4.setSelectedItem(nombreLibro4Modificar);
        textAutorLibro5.setSelectedItem(autorLibro5Modificar);
        textNombreLibro5.setSelectedItem(nombreLibro5Modificar);
        */
        
        if(estado == true){
            botonEstado.setSelected(true);
        }
        else{
            botonEstado.setSelected(false);
        }
    }
    
    
    private void autorLibroListado(JComboBox AutorLibro, JComboBox NombreLibro, JTextField IdLibro, JTextField PrecioLibro) {                                            
        // TODO add your handling code here:
        float precioLibro1, precioLibro2, precioLibro3, precioLibro4, precioLibro5, precioTotal;
        //libros.Conectar();//Eliminar
        if(AutorLibro.getSelectedIndex() > -1)
        {
            String autorLibro = AutorLibro.getSelectedItem().toString();
            
            if(autorLibro.equals("Seleccione autor")){
                IdLibro.setText(null);
                PrecioLibro.setText(null);
                NombreLibro.removeAllItems();
            }
            else{
                libros.setAutor(autorLibro);
                libros.ListadoNombresLibros(NombreLibro);
            }
            
            precioLibro1 = costoLibro(textPrecioLibro1);
            precioLibro2 = costoLibro(textPrecioLibro2);
            precioLibro3 = costoLibro(textPrecioLibro3);
            precioLibro4 = costoLibro(textPrecioLibro4);
            precioLibro5 = costoLibro(textPrecioLibro5);

            precioTotal = precioLibro1 + precioLibro2 + precioLibro3 + precioLibro4 + precioLibro5;
            
            if(precioTotal == 0)
            {
                textTotal.setText("");
            }
            else
            {
               textTotal.setText(String.valueOf(precioTotal)); 
            }    
        }
        //libros.Desconectar();//Eliminar
    }
        
    private void nombreLibroListado(JComboBox NombreLibro, JComboBox AutorLibro, JTextField IdLibro, JTextField PrecioLibro){
        // TODO add your handling code here:       
        float precioLibro1, precioLibro2, precioLibro3, precioLibro4, precioLibro5, precioTotal;
        //libros.Conectar();//Eliminar
        if(NombreLibro.getSelectedIndex() > -1)
        {
            String autorLibro = AutorLibro.getSelectedItem().toString();
            
            if(autorLibro.equals("Seleccione autor")){
                IdLibro.setText(null);
                PrecioLibro.setText(null);
            }
            else{
                String nombreLibro = NombreLibro.getSelectedItem().toString();
                libros.setNombre(nombreLibro);
                libros.IdLibro();
                libros.PrecioLibro();
                IdLibro.setText(String.valueOf(libros.getId()));
                PrecioLibro.setText(String.valueOf(libros.getPrecio()));
            }
            
            precioLibro1 = costoLibro(textPrecioLibro1);
            precioLibro2 = costoLibro(textPrecioLibro2);
            precioLibro3 = costoLibro(textPrecioLibro3);
            precioLibro4 = costoLibro(textPrecioLibro4);
            precioLibro5 = costoLibro(textPrecioLibro5);
            
            precioTotal = precioLibro1 + precioLibro2 + precioLibro3 + precioLibro4 + precioLibro5;
            
            if(precioTotal == 0)
            {
                textTotal.setText("");
            }
            else
            {
               textTotal.setText(String.valueOf(precioTotal)); 
            }  
        }
        //libros.Desconectar();//Eliminar
    }
    
    private float costoLibro(JTextField PrecioLibro) {                                            
        // TODO add your handling code here:
        float precioLibro;
                
        if(PrecioLibro.getText().equals(""))
        {
            precioLibro = 0; 
        }
        else
        {
            precioLibro = Float.parseFloat(PrecioLibro.getText());
        }
        
        return precioLibro;
    }
}
